Added WaitForJobs to ChartSpec
mittwald/go-helm-client pull request #67
Opened 2022-03-22 12:32 UTC by zvonkok

If set and `Wait` enabled, will wait until all Jobs have been completed before marking the release as successful. It will wait for as long as `Timeout`

2022-03-24 10:59 UTC, zvonkok commented
@elenz97 PTAL if you have some time. Thanks.

2022-04-04 07:50 UTC, elenz97 requested changes
Hey @zvonkok, thanks for your contribution! Just a small nitpick on the field comment from my side.

2022-04-04 07:50 UTC, elenz97 commented on types.go
> +	// for as long as Timeout
```suggestion
	// WaitForJobs indicates whether to wait for completion of release Jobs before marking the release as successful.
	// 'Wait' has to be specified for this to take effect.
	// The timeout may be specified via the 'Timeout' field.
```

2022-04-04 07:56 UTC, zvonkok commented on types.go
> +	// for as long as Timeout
Sounds better, pushed :)

2022-04-04 08:32 UTC, elenz97 approved these changes

2022-04-04 08:33 UTC, merged