Added generate name if release or name is empty
mittwald/go-helm-client pull request #74
Opened 2022-04-05 16:26 UTC by zvonkok

Fixes https://github.com/mittwald/go-helm-client/issues/69

2022-04-05 16:27 UTC, zvonkok commented
@elenz97 PTAL

2022-04-06 06:38 UTC, elenz97 requested changes
Hey @zvonkok and thanks again for your contribution(s)!
Just a small nitpick on the code comments :+1:

2022-04-06 06:38 UTC, elenz97 commented on client.go
> +	// second the ReleaseName if set, and lastly the generatedName
How about:
```suggestion
	// NameAndChart returns either the TemplateName if set,
	// the ReleaseName if set or the generatedName as the first return value.
```
?

2022-04-06 06:38 UTC, elenz97 commented on client.go
> +	// second the ReleaseName if set, and lastly the generatedName
see above

2022-04-06 08:52 UTC, zvonkok commented on client.go
> +	// second the ReleaseName if set, and lastly the generatedName
Updated both to your suggestion.

2022-04-06 09:16 UTC, elenz97 approved these changes
Looking good, thanks again @zvonkok!

2022-04-06 09:16 UTC, merged